--Aggregate Functions
SELECT COUNT(TITLE) FROM MOVIES;
SELECT COUNT(TITLE) FROM TV_SERIES;

--Nested Queries
SELECT TITLE FROM MOVIES WHERE RATE IN (SELECT MAX(RATE) FROM MOVIES);
SELECT TITLE FROM TV_SERIES WHERE RATE IN (SELECT MAX(RATE) FROM TV_SERIES);

--Triggers
--1
CREATE TRIGGER insmov BEFORE DELETE ON MOVIES
FOR EACH ROW
INSERT INTO DELMOVIES (title, genre) VALUES(old.title, old.genre);

--2
CREATE TRIGGER instvs BEFORE DELETE ON TV_SERIES
FOR EACH ROW
INSERT INTO DELTV_SERIES (title, genre) VALUES(old.title, OLD.genre);

--DML commands
SELECT * FROM MOVIES;
SELECT * FROM TV_SERIES;

