CREATE DATABASE movie;
USE movie ;

CREATE TABLE delmovies (
  id INT(11) NOT NULL AUTO_INCREMENT,
  title VARCHAR(100) DEFAULT NULL,
  genre VARCHAR(50) DEFAULT NULL,
  `deleted at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id));


CREATE TABLE deltv_series (
  id INT(11) NOT NULL AUTO_INCREMENT,
  title VARCHAR(100) DEFAULT NULL,
  genre VARCHAR(50) DEFAULT NULL,
  `deleted at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id));

CREATE TABLE genre (
  ID INT(11) NOT NULL,
  NAME VARCHAR(45) NOT NULL,
  PRIMARY KEY (NAME));

CREATE TABLE ratings (
  ID INT(11) NOT NULL,
  IMDB FLOAT(4,2) NOT NULL,
  PRIMARY KEY (IMDB));

CREATE TABLE movies (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(100) NOT NULL,
  IMAGES LONGBLOB NULL DEFAULT NULL,
  `RELEASE YEAR` YEAR(4) NOT NULL,
  RUNTIME INT(11) NOT NULL,
  DIRECTOR VARCHAR(50) NOT NULL,
  CAST TEXT NOT NULL,
  GENRE VARCHAR(45) NOT NULL,
  RATE FLOAT(4,2) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (GENRE) REFERENCES genre(NAME),
  FOREIGN KEY (RATE) REFERENCES ratings(IMDB));

CREATE TABLE tv_series (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(100) NOT NULL,
  IMAGES LONGBLOB NULL DEFAULT NULL,
  SEASONS INT(11) NOT NULL,
  CAST TEXT NOT NULL,
  DIRECTOR VARCHAR(50) NOT NULL,
  GENRE VARCHAR(45) NOT NULL,
  RATE FLOAT(4,2) NOT NULL,
  STATUS VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (GENRE) REFERENCES genre(NAME),
  FOREIGN KEY (RATE) REFERENCES ratings(IMDB));


CREATE TRIGGER insmov BEFORE DELETE ON movies
FOR EACH ROW
insert into delmovies (title, genre) values(old.title, old.genre);


CREATE TRIGGER instvs BEFORE DELETE ON tv_series
FOR EACH ROW
insert into deltv_series(title, genre) values(old.title, old.genre);




